# This config file for Travis CI utilizes ros-industrial/industrial_ci package.
# For more info for the package, see https://github.com/ros-industrial/industrial_ci/blob/master/README.rst
services:
  - docker
language: generic
compiler:
  - gcc

env:
  matrix:
  # add NOT_TEST_BUILD=true NOT_TEST_INSTALL=true to skip build or install tests
    - ROS_DISTRO="indigo"  DOCKER_IMAGE=indigo-trusty-shadow-fixed
    - ROS_DISTRO="kinetic" DOCKER_IMAGE=kinetic-xenial-shadow-fixed
    - ROS_DISTRO="lunar"   DOCKER_IMAGE=lunar-xenial-shadow-fixed

install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config

script:
  - .ci_config/travis.sh

notifications:
  email: false
